name: AmethystApath
version: ${project.version}
main: me.cloudsven.amethystapath.AmethystApath
api-version: '1.21'
authors: [ cloudsven ]
description: Some much needed additions to Amethyst.
website: cloudsven.com
depend: [CarpetTIS]

commands:
  amethystapath:
    description: Main AmethystApath command
    usage: /amethystapath
    aliases: [aa]

permissions:
  amethystapath.admin:
    description: Allows admin permissions
    default: op